components.json
package-lock.json
package.json
src/app/dashboard/page.tsx
src/app/globals.css
src/app/layout.tsx
src/components/app-sidebar.tsx
src/components/nav-main.tsx
src/components/nav-projects.tsx
src/components/nav-secondary.tsx
src/components/nav-user.tsx
src/components/ui/avatar.tsx
src/components/ui/breadcrumb.tsx
src/components/ui/button.tsx
src/components/ui/collapsible.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/input.tsx
src/components/ui/separator.tsx
src/components/ui/sheet.tsx
src/components/ui/sidebar.tsx
src/components/ui/skeleton.tsx
src/components/ui/tooltip.tsx
src/hooks/use-mobile.tsx
src/lib/utils.ts
tailwind.config.ts

setup the main layout for the authenticated users.
Screenshot:

1 setup main layout for the authenticated users of application

---

next.config.ts

**Remove static route, Lightning symbol at bottom left corner.**

removed static route, lightning symbol

---

src/app/courses/page.tsx
src/app/export/page.tsx
src/app/students/page.tsx
src/components/app-sidebar.tsx

Create initial components:
- Export/Share
- Courses
- Students
**Export**
**Courses**
**Students**

#9 make initial components and integrate datatable

---

src/app/courses/page.tsx
src/app/export/page.tsx
src/app/students/page.tsx
src/components/app-sidebar.tsx

Updating feature branch `13-make-crud-operations-for-courses` with `main`

#9 make initial components and integrate datatable (#17)

---

src/app/courses/page.tsx
src/components/re-useables/SmartSelect/page.tsx

Test this columns dropdown and compare its functionality with the same dropdown in the `students` page 
| https://localhost:3000/courses |
|-------|
| ![Dropdown Screenshot](https://github.com/user-attachments/assets/3e47d7f7-f59f-4fb2-8fbe-fb439ae675ea) |

Add re-useable component

---

src/app/courses/page.tsx
src/components/re-useables/SmartSelect/page.tsx

Pull changes in the feature branch #16 from main

Add re-useable component (#21)

---

src/app/attendance/page.tsx
src/app/courses/page.tsx
src/app/export/page.tsx
src/app/students/page.tsx

#24 replace all dropdowns in the app with smart select

---

package-lock.json
package.json
src/app/courses/page.tsx
src/app/model/student.ts
src/app/students/add-student.tsx
src/app/students/page.tsx
src/components/ui/dialog.tsx
src/components/ui/form.tsx
src/components/ui/label.tsx

16 make crud operations in students screen

---

src/app/courses/page.tsx

Fetch latest changes from main to feature branch #26

remove duplicate import from courses (#38)

---

src/app/courses/page.tsx
src/app/students/page.tsx
src/app/students/update-student.tsx

26 add new functionality for viewing and updating student in students

---

src/app/model/student.ts
src/app/students/add-student.tsx
src/app/students/update-student.tsx

46 validation error on students

---

src/app/courses/page.tsx

Please verify on local before approving

Add functionality to delete the course

---

src/app/courses/add-course.tsx
src/app/courses/page.tsx
src/app/courses/update-course.tsx
src/app/students/add-student.tsx
src/app/students/page.tsx
src/app/students/update-student.tsx
src/components/app-sidebar.tsx
src/components/nav-main.tsx
src/components/nav-user.tsx
src/components/ui/calendar.tsx

✔ No ESLint warnings or errors

Remove ESLint warnings or errors

---

.github/workflows/build-pipeline.yml
package-lock.json
package.json

* Create nextjs.yml
* Update nextjs.yml
* Update nextjs.yml
* Update nextjs.yml
* Take pull from main (#58)
* Add functionality to delete the course (#53)
* Remove ESLint warnings or errors (#57)
* Remove ESLint warnings or errors
* fix bugs
* Add sharp package
* Pull changes from the main (#60)
* Add functionality to delete the course (#53)
* Remove ESLint warnings or errors (#57)
* Remove ESLint warnings or errors
* fix bugs
* Update nextjs.yml
* Pull changes from main (#64)
* Add functionality to delete the course (#53)
* Remove ESLint warnings or errors (#57)
* Remove ESLint warnings or errors
* fix bugs
* Update datagrid fields (#63)
* Add secrets as environment variable
* Add out folder for the build artifacts
* Delete out directory
* Remove extra code for build pipeline
* Update …

Create build pipeline for continuous integration (#55)

---

.github/workflows/build-pipeline.yml
package-lock.json
package.json
src/app/courses/add-course.tsx
src/app/courses/page.tsx
src/app/courses/update-course.tsx
src/components/re-useables/ActionButton/Page.tsx

Anyone who is approving this PR must check all operations listed in issue #62

Fix bug in modal pop ups

---

src/app/courses/new/loading.tsx
src/app/courses/new/page.tsx
src/app/courses/page.tsx
src/app/courses/update/[key]/loading.tsx
src/app/courses/update/[key]/page.tsx
src/app/models/course.ts
src/app/students/page.tsx
src/components/courses/form.tsx
src/components/courses/grid.tsx

* 89 refactor course screen (#91) (#94)
* Added loading ui and index.ts for centralized imports
* Refactor the course screen and added loading ui in course component
* Add meta data to courses/update course/new
* Remove linting errors
* Stabilize the build
* WIP
* Complete integrating endpoint in `/course` screen

72 integrate course with backend endpoints (#97)

---

src/app/models/student.ts
src/app/students/page.tsx
src/components/class-representatives/form.tsx
src/components/re-useables/ActionButton/component.tsx
src/components/students/grid.tsx
src/components/students/nominate.tsx

Implement CR functionality in /students screen

add cr func in /students screen

---

src/app/models/student.ts
src/app/students/update/[key]/page.tsx
src/components/class-representatives/form.tsx
src/components/students/form.tsx
src/components/students/grid.tsx

Check that student have the email field everywhere in the systemyetsm

Add email field to student form and update related components

---

package-lock.json
package.json
src/components/attendance/grid.tsx
src/components/ui/popover.tsx

- filter by date 
- filter by date range
- filter data using search

81 attendance screen UI features

---

src/app/automark/page.tsx
src/components/AttendanceList.tsx
src/components/VideoStream.tsx
src/components/nav-main.tsx
src/components/nav-user.tsx
src/styles/Home.module.css
src/utils/azureFaceApi.ts

This pull request introduces a new AI-powered attendance marking feature. The main changes include the addition of a new page for the feature, components for video streaming and attendance listing, styles for the new page, and utility functions for interacting with the Azure Face API.
New Feature Implementation:
* [`src/app/automark/page.tsx`](diffhunk://#diff-7bf9f2b182e8580aad452523cb4e172dd3ae24303b98d18a7f544819980bd822R1-R33): Added a new page component `AutoMarkPage` that integrates video streaming and attendance listing functionalities. It uses state management to track attendance events.
Components for Video Streaming and Attendance Listing:
* [`src/components/VideoStream.tsx`](diffhunk://#diff-578f969cdb189c7d9f3af1ef48f50f688324851d54efdf9dd5cf21b304e2d52dR1-R84): Added a new …

POC integrated in project
